# -*- coding: utf-8 -*-
"""Kopie van Kopie van Welcome bij Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPLK_8sWwzztMR8PuxUuftYwtvL7bwS_

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Wat is Colaboratory?</h1>

Met Colaboratory &#40;kortweg Colab&#41; kun je Python uitvoeren in je browser
- Zonder vereiste configuratie
- Met gratis toegang tot GPU's
- En makkelijk delen

Of je nu een <strong>student</strong>, <strong>datawetenschapper</strong> of <strong>AI-onderzoeker</strong> bent, Colab kan je werk makkelijker maken. Bekijk <a href="https://www.youtube.com/watch?v=inN8seMm7UI">Kennismaken met Colab</a> voor meer informatie of ga hieronder meteen aan de slag.
"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import io
df = pd.read_csv(io.BytesIO(data_to_load['day-overview-201503.csv']))
df.plot(x='Day', y='NumberOfSubmission', kind = 'scatter')
plt.xticks(df["Day"])
plt.show()
df.plot(x='Day', y='SumOfProgress', kind = 'scatter')
plt.xticks(df["Day"])
plt.show()
df.plot(x='Day', y='NumberOfWorkedPupil', kind = 'scatter')
plt.xticks(df["Day"])
plt.show()
df.plot(x='Day', y='NumberOfProgresseddPupil', kind = 'scatter')
plt.xticks(df["Day"])
plt.show()

df

"""## <strong>Aan de slag</strong>

Het document dat je leest, is geen statische webpagina maar een interactieve omgeving die we een <strong>Colab-notebook</strong> &#40;kladblok&#41; noemen en waarmee je code kunt schrijven en uitvoeren.

Hier zie je bijvoorbeeld een <strong>codecel</strong> met een kort Python-script waarmee een waarde wordt berekend. Deze waarde wordt opgeslagen in een variabele en het resultaat wordt afgedrukt:
"""

import pandas as pd
import matplotlib.pyplot as plt



seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""Als je de code in de bovenstaande cel wilt uitvoeren, selecteer je deze met een klik en dan klik je links van de code op de afspeelknop of gebruik je de sneltoets 'Command/Ctrl + Enter'. Als je de code wilt bewerken, klik je op de cel en begin je met bewerken.

Variabelen die je in de ene cel definieert, kunnen later worden gebruikt in andere cellen:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Met Colab-notebooks kun je <strong>uitvoerbare code</strong> binnen één document combineren met <strong>tekst met opmaak</strong>, <strong>afbeeldingen</strong>, <strong>html</strong>, <strong>LaTeX</strong> en meer. Als je je eigen Colab-notebooks maakt, worden deze opgeslagen in je Google Drive-account. Je kunt je Colab-notebooks makkelijk delen met collega's of vrienden. Zij kunnen dan reacties over je notebooks achterlaten of ze zelfs bewerken. Bekijk het <a href="/notebooks/basic_features_overview.ipynb">Overzicht van Colab</a> voor meer informatie. Je kunt een nieuw Colab-notebook maken via het menu 'Bestand' bovenaan, of je kunt de volgende link gebruiken: <a href="http://colab.research.google.com#create=true">een nieuwe Colab-notebook maken</a>.

Colab-notebooks zijn Jupyter-notebooks die worden gehost door Colab. Zie <a href="https://www.jupyter.org">jupyter.org</a> voor meer informatie over het Jupyter-project.

## Datawetenschap

Met Colab kun je de volledige kracht van populaire Python-bibliotheken benutten om gegevens te analyseren en visualiseren. De onderstaande codecel gebruikt <strong>numpy</strong> om een aantal willekeurige gegevens te genereren en <strong>matplotlib</strong> om deze te visualiseren. Als je de code wilt bewerken, klik je op de cel en begin je met bewerken.
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""Je kunt je eigen gegevens naar je Colab-notebooks importeren vanuit je Google Drive-account, inclusief gegevens uit spreadsheets, vanuit GitHub en vele andere bronnen. Bekijk de links onder <a href="#working-with-data">Werken met gegevens</a> hieronder voor meer informatie over het importeren van gegevens en hoe je Colab kunt gebruiken voor datawetenschap.

## Machine learning

Met Colab kun je een dataset met afbeeldingen importeren, een afbeeldingsclassificatie erop trainen en het model evalueren. En dit alles met slechts <a href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb">een paar regels code</a>. Colab-notebooks voeren de code uit op de cloudservers van Google. Dat houdt in dat je gebruik kunt maken van de kracht van Google-hardware &#40;inclusief <a href="#using-accelerated-hardware">GPU's en TPU's</a>&#41;, ongeacht de kracht van je machine. Je hebt alleen maar een browser nodig.

Colab wordt zeer veel gebruikt in de machinelearning-community, met toepassingen zoals:
- Aan de slag met TensorFlow
- Neurale netwerken ontwikkelen en trainen
- Experimenteren met TPU's
- De verspreiding van AI-onderzoek
- Tutorials maken

Bekijk de <a href="#machine-learning-examples">voorbeelden van machine learning</a> hieronder in Colab-notebooks met machinelearning-toepassingen.

## Meer bronnen

### Werken met notebooks in Colab
- [Overzicht van Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Gids voor Markdown](/notebooks/markdown_guide.ipynb)
- [Bibliotheken importeren en afhankelijkheden installeren](/notebooks/snippets/importing_libraries.ipynb)
- [Notebooks opslaan en laden in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [Interactieve formulieren](/notebooks/forms.ipynb)
- [Interactieve widgets](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [TensorFlow 2 in Colab](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### Werken met gegevens
- [Gegevens laden: Drive, Spreadsheets en Google Cloud Storage](/notebooks/io.ipynb) 
- [Diagrammen: gegevens visualiseren](/notebooks/charts.ipynb)
- [Aan de slag met BigQuery](/notebooks/bigquery.ipynb)

### Spoedcursus machine learning
Dit zijn enkele van de notebooks van de online cursus Machine Learning van Google. Bekijk de <a href="https://developers.google.com/machine-learning/crash-course/">volledige cursuswebsite</a> voor meer informatie.
- [Inleiding tot Pandas DataFrame](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [Lineaire regressie met tf.keras via synthetische gegevens](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb)


<a name="using-accelerated-hardware"></a>
### Versnelde hardware gebruiken
- [TensorFlow met GPU's](/notebooks/gpu.ipynb)
- [TensorFlow met TPU's](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

## Voorbeelden van machine learning

Als je enkele uitgebreide voorbeelden wilt bekijken van de interactieve machinelearning-analyses die door Colaboratory mogelijk worden gemaakt, bekijk je deze tutorials waarin modellen van <a href="https://tfhub.dev">TensorFlow Hub</a> worden gebruikt.

Een paar uitgelichte voorbeelden:

- <a href="https://tensorflow.org/hub/tutorials/tf2_image_retraining">Een afbeeldingsclassificatiefunctie opnieuw trainen</a>: ontwerp een Keras-model bovenop een vooraf getrainde afbeeldingsclassificatiefunctie om bloemen van elkaar te onderscheiden.
- <a href="https://tensorflow.org/hub/tutorials/tf2_text_classification">Tekstclassificatie</a>: classificeer IMDB-filmreviews als <em>positief</em> of <em>negatief</em>.
- <a href="https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization">Stijloverdracht</a>: gebruik deep learning om stijlen over te dragen tussen afbeeldingen.
- <a href="https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa">Veelgestelde vragen over de Multilingual Universal Sentence Encoder</a>: gebruik een model voor machine learning om vragen uit de SQuAD-dataset te beantwoorden.
- <a href="https://tensorflow.org/hub/tutorials/tweening_conv3d">Video-interpolatie</a>: voorspel wat er in een video is gebeurd tussen het eerste en laatste frame.
"""