//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snappet.core.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDomainLink
    {
        public int SD_LinkID { get; set; }
        public int SubjectID { get; set; }
        public int DomainID { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
