//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snappet.core.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedAnswer
    {
        public int SubmittedAnswerID { get; set; }
        public bool Correct { get; set; }
        public System.DateTime SubmittedAnswerDateTime { get; set; }
        public int Progress { get; set; }
        public int UserID { get; set; }
        public int ExerciseID { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual User User { get; set; }
    }
}
