//-----------------------------------------------------------------------
// <copyright file="RoleDto.cs" company="Harbor Village">
//     Copyright (c) Harbor Village. All rights reserved.
// </copyright>
// <auto-generated />
// <author></author>
//-----------------------------------------------------------------------
namespace Nicollas.Dto.Identity
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// This class is a Role DTO <see cref="Entities.Identity.Role"/>
    /// </summary>
    public class RoleDto: BaseEntityDto<Guid>
    {
        /// <summary>
        /// Gets or sets a navigation property for the users in this role.
        /// </summary>
        public virtual ICollection<UserRoleDto> Users { get; set; }

        /// <summary>
        /// Gets or sets a navigation property for claims in this role.
        /// </summary>
        public virtual ICollection<RoleClaimDto> Claims { get; set; }

        /// <summary>
        /// Gets or sets the name for this role.
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// Gets or sets the normalized name for this role.
        /// </summary>
        public virtual string NormalizedName { get; set; }

        /// <summary>
        /// Gets or sets the strong of this role, It means, Roles that have an strong lower than another can't see or alter it.
        /// </summary>
        public virtual float Strong { get; set; }

        /// <summary>
        /// Gets or sets a random value that should change whenever a role is persisted to the store
        /// </summary>
        public virtual string ConcurrencyStamp { get; set; }
    }
}
