//-----------------------------------------------------------------------
// <copyright file="UserRoleDto.cs" company="Harbor Village">
//     Copyright (c) Harbor Village. All rights reserved.
// </copyright>
// <auto-generated />
// <author></author>
//-----------------------------------------------------------------------
namespace Nicollas.Dto.Identity
{
    using System;

    /// <summary>
    /// This class is a UserRole DTO <see cref="Entities.Identity.UserRole"/>
    /// </summary>
    public class UserRoleDto
    {
         /// <summary>
        /// Gets or sets the primary key of the user that is linked to a role.
        /// </summary>
        public virtual Guid UserId { get; set; }

        /// <summary>
        ///  Gets or sets the user
        /// </summary>
        public virtual UserDto User { get; set; }

        /// <summary>
        /// Gets or sets the primary key of the role that is linked to the user.
        /// </summary>
        public virtual Guid RoleId { get; set; }

        /// <summary>
        ///  Gets or sets the role
        /// </summary>
        public virtual RoleDto Role { get; set; }
    }
}
