//-----------------------------------------------------------------------
// <copyright file="UserClaimDto.cs" company="Harbor Village">
//     Copyright (c) Harbor Village. All rights reserved.
// </copyright>
// <auto-generated />
// <author></author>
//-----------------------------------------------------------------------
namespace Nicollas.Dto.Identity
{
    using System;

    /// <summary>
    /// This class is a UserClaim DTO <see cref="Entities.Identity.UserClaim"/>
    /// </summary>
    public class UserClaimDto
    {
        /// <summary>
        /// Gets or sets the primary key of the user associated with this claim.
        /// </summary>
        public virtual Guid UserId { get; set; }

        /// <summary>
        ///  Gets or sets the user
        /// </summary>
        public virtual UserDto User { get; set; }

        /// <summary>
        /// Gets or sets the claim type for this claim.
        /// </summary>
        public virtual string ClaimType { get; set; }

        /// <summary>
        /// Gets or sets the claim value for this claim.
        /// </summary>
        public virtual string ClaimValue { get; set; }
    }
}
