//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.TestResources", typeof(TestResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;SubmittedAnswerId&quot;:61717849,
        ///    &quot;SubmitDateTime&quot;:&quot;2015-03-23T08:24:44.420&quot;,
        ///    &quot;Correct&quot;:1,
        ///    &quot;Progress&quot;:7,
        ///    &quot;UserId&quot;:68421,
        ///    &quot;ExerciseId&quot;:389764,
        ///    &quot;Difficulty&quot;:&quot;216.4190329&quot;,
        ///    &quot;Subject&quot;:&quot;Rekenen&quot;,
        ///    &quot;Domain&quot;:&quot;Getallen&quot;,
        ///    &quot;LearningObjective&quot;:&quot;Afronden op hele getallen&quot;
        ///  },
        ///  {
        ///    &quot;SubmittedAnswerId&quot;:69399577,
        ///    &quot;SubmitDateTime&quot;:&quot;2015-03-24T11:29:58.530&quot;,
        ///    &quot;Correct&quot;:1,
        ///    &quot;Progress&quot;:0,
        ///    &quot;UserId&quot;:40282,
        ///    &quot;ExerciseId&quot;:392536,
        ///    &quot;Difficulty&quot;:&quot;211.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleJsonWork {
            get {
                return ResourceManager.GetString("SampleJsonWork", resourceCulture);
            }
        }
    }
}
