//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snappet.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snappet.Helpers.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Objectives.
        /// </summary>
        public static string LearningObjectives {
            get {
                return ResourceManager.GetString("LearningObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Activity.
        /// </summary>
        public static string StudentsActivity {
            get {
                return ResourceManager.GetString("StudentsActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Data.
        /// </summary>
        public static string StudentsData {
            get {
                return ResourceManager.GetString("StudentsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Total Correct.
        /// </summary>
        public static string TotalCorrect {
            get {
                return ResourceManager.GetString("TotalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Total Domains.
        /// </summary>
        public static string TotalDomains {
            get {
                return ResourceManager.GetString("TotalDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Total Learning Objective.
        /// </summary>
        public static string TotalLearningObjective {
            get {
                return ResourceManager.GetString("TotalLearningObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Total Progress.
        /// </summary>
        public static string TotalProgress {
            get {
                return ResourceManager.GetString("TotalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Total Students.
        /// </summary>
        public static string TotalStudents {
            get {
                return ResourceManager.GetString("TotalStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Total Subjects.
        /// </summary>
        public static string TotalSubjects {
            get {
                return ResourceManager.GetString("TotalSubjects", resourceCulture);
            }
        }
    }
}
