//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnappetChallenge.DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class SnappetDal : global::System.Configuration.ApplicationSettingsBase {
        
        private static SnappetDal defaultInstance = ((SnappetDal)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SnappetDal())));
        
        public static SnappetDal Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\git\\Snappet\\Data\\work.json")]
        public string DefaultWorkJsonpath {
            get {
                return ((string)(this["DefaultWorkJsonpath"]));
            }
        }
    }
}
