// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Snappet.Assignment.Data.Context;
using System;

namespace Snappet.Assignment.WebApp.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20180206201516_InitialMigrations-1")]
    partial class InitialMigrations1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("School")
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Snappet.Assignment.Entities.DomainObjects.Exercise", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Snappet.Assignment.Entities.DomainObjects.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Snappet.Assignment.Entities.DomainObjects.Work", b =>
                {
                    b.Property<int>("SubmittedAnswerId");

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("float");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("LearningObjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<short>("Progress")
                        .HasColumnType("smallint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("SubmitDateTime")
                        .HasColumnType("dateTime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubmittedAnswerId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Snappet.Assignment.Entities.DomainObjects.Work", b =>
                {
                    b.HasOne("Snappet.Assignment.Entities.DomainObjects.Exercise", "Exercise")
                        .WithMany("Works")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Snappet.Assignment.Entities.DomainObjects.User", "User")
                        .WithMany("Works")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
