import * as React from 'react';
import { Link } from 'react-router';

export default class Home extends React.Component<void, void> {
	public render() {
		return <div>
			<h1 className="c-heading"
				style={{ paddingTop: 0 }}>Hello!</h1>
			<p className="c-paragraph">This application is based on the <a href="https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices">AspNetCore.SpaServices</a> template provided by Microsoft.</p>
			<section>
				<h2 className="c-heading">The report</h2>
				<p className="c-paragraph">
					The report I came up with is at the <Link to={`/userstats`}>Overview</Link> page. Check it out! The application considers today to be <span className="c-text--highlight">2015-03-24 11:30:00 UTC</span> and will not allow you to "see" past that date.
				</p>
				<p className="c-paragraph">
					The progress graphs don't cover the entire period,
					they just show 10 most recent non-zero increments within the period.
				</p>
			</section>

			<div className="c-card u-higher">
				<div className="c-card__item c-card__item--brand">Libraries</div>
				<div className="c-card__item u-pillar-box--medium">
					<p className="c-paragraph">Here is the list of notable libraries:</p>
					<ul className="c-list">
							<li className="c-list__item"><a href="http://blazecss.com">BlazeCSS</a> + <a href="http://fontawesome.io/">Font awesome</a> instead of Bootstrap, because I wanted to learn something new <i className="fa fa-smile-o"></i>.</li>
							<li className="c-list__item"><a href="https://github.com/borisyankov/react-sparklines">React sparklines</a> for drawing small graphs.</li>
							<li className="c-list__item"><a href="https://autofac.org/">Autofac</a> for dependency injection.</li>
							<li className="c-list__item"><a href="https://docs.microsoft.com/en-us/ef/core/">EF Core</a> for object-relational mapping.</li>
						</ul>
				</div>
			</div>

			<div className="c-alert" style={{marginTop: "2em"}}>
				The rest of the page is just a default text generated by the template.
			</div>


			<p>To help you get started, we've also set up:</p>
			<ul>
				<li><strong>Client-side navigation</strong>. For example, click <em>Counter</em> then <em>Back</em> to return here.</li>
				<li><strong>Webpack dev middleware</strong>. In development mode, there's no need to run the <code>webpack</code> build tool. Your client-side resources are dynamically built on demand. Updates are available as soon as you modify any file.</li>
				<li><strong>Hot module replacement</strong>. In development mode, you don't even need to reload the page after making most changes. Within seconds of saving changes to files, rebuilt React components will be injected directly into your running application, preserving its live state.</li>
				<li><strong>Efficient production builds</strong>. In production mode, development-time features are disabled, and the <code>webpack</code> build tool produces minified static CSS and JavaScript files.</li>
				<li><strong>Server-side prerendering</strong>. To optimize startup time, your React application is first rendered on the server. The initial HTML and state is then transferred to the browser, where client-side code picks up where the server left off.</li>
			</ul>
		</div>;
	}
}
