// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snappet.ClassInsights.Orm;

namespace Snappet.ClassInsights.Orm.Migrations
{
    [DbContext(typeof(InsightsContext))]
    partial class InsightsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Snappet.ClassInsights.Model.Domain.SubmittedAnswer", b =>
                {
                    b.Property<long>("SubmittedAnswerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Correct");

                    b.Property<string>("Difficulty");

                    b.Property<string>("Domain");

                    b.Property<long>("ExerciseId");

                    b.Property<string>("LearningObjective");

                    b.Property<int>("Progress");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("SubmitDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("SubmittedAnswerId");

                    b.ToTable("SubmittedAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
