// <auto-generated>
//-----------------------------------------------------------------------
// <copyright file="BaseEntityDto.cs" company="Harbor Village">
//     Copyright (c) Harbor Village. All rights reserved.
// </copyright>
// <author></author>
//-----------------------------------------------------------------------
namespace Nicollas.Dto
{
    using System;

    /// <summary>
    /// This class is the DTO representation of <see cref="BaseEntity"/>
    /// </summary>
    /// <typeparam name="TKey">The type of the key</typeparam>
    public abstract class BaseEntityDto<TKey>
    {
        /// <summary>
        /// Gets or sets the key for all the entities
        /// </summary>
        public TKey Id { get; set; }

        /// <summary>
        /// Gets or sets the create at
        /// </summary>
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the update at
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the Entity is trash (should only be seen on reports)
        /// </summary>
        public bool Trash { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether the Entity is disabled (should not be seen by common users)
        /// </summary>
        public bool Disabled { get; set; } = false;
    }
}
