// <auto-generated />
using EFGetStarted.AspNetCore.NewDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace SnappetChallenge.Core.Migrations
{
    [DbContext(typeof(ClassReportContext))]
    [Migration("20180417115200_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.ReportItem", b =>
                {
                    b.Property<int>("SubmittedAnswerId");

                    b.Property<int>("Correct");

                    b.Property<decimal?>("Difficulty");

                    b.Property<string>("Domain");

                    b.Property<int>("ExerciseId");

                    b.Property<string>("LearningObjective");

                    b.Property<int>("Progress");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("SubmitDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("SubmittedAnswerId");

                    b.HasIndex("SubmitDateTime");

                    b.ToTable("ReportItems");
                });
#pragma warning restore 612, 618
        }
    }
}
